### ISSUE TITLE
Issue with Path Browser Validation

### ISSUE THREAD

**Issue by sat-sap** [wcm-io/io.wcm.caconfig.editor#65]
Hi Team ,

I am trying to apply validation to a pathbrowser field in a context-aware configuration, but the validation is not being triggered. Validation works fine for text and textarea fields, but not for the pathbrowser.

I tested both the ootb **wcmio.path** validation and a custom validation, but neither works. 
For example, I have a configuration that allows selecting a content path and I want to validate that the field is not empty or that the path is valid path. 

<img width="854" height="371" alt="Image" src="https://github.com/user-attachments/assets/b80c06e9-0d22-4774-b2c3-5621ce8e2c7a" />

While wcmio.path should handle this, it doesn’t seem to function as expected for the pathbrowser. 
<img width="1446" height="232" alt="Image" src="https://github.com/user-attachments/assets/b20c10b1-0489-442d-862f-0713de233e98" />

However, the same validation rules work correctly for text and textarea fields.

<img width="876" height="280" alt="Image" src="https://github.com/user-attachments/assets/33e1877f-f176-458c-ac3e-5ffdab00f49c" />

<img width="1463" height="287" alt="Image" src="https://github.com/user-attachments/assets/afa4f2f7-0456-4dd7-98ec-93fe3c2f1b19" />

**Comment by stefanseifert** [comment]
you're right! - although documented as such, validation support was never implemented for pathbrowser widgets.

PR https://github.com/wcm-io/io.wcm.caconfig.editor/pull/66 should fix this - @sat-sap can you give it a try?

**Comment by sat-sap** [comment]
Thank you @stefanseifert  for the quick response. I tested it with sample app and it works. But it’s still not working in our project using version 1.16.7-SNAPSHOT,so I’ll debug the issue further.

**Comment by stefanseifert** [comment]
make sure it's not a caching issue - if you are testing locally, try to invalidate the script cache via http://localhost:4502/libs/granite/ui/content/dumplibs.rebuild.html

**Comment by sat-sap** [comment]
it worked.Thank you.

**Comment by sat-sap** [comment]
@stefanseifert Do you have a timeline for when the next release containing the fix is expected?

**Comment by stefanseifert** [comment]
i will do a release monday 8th by latest - if you need it earlier, that's possible as well

**Comment by sat-sap** [comment]
For us monday(8th dec) is fine.Thank you.
